/**
 * G-code generator — converts sliced layers into Marlin/RepRap G-code.
 */

import type { SliceLayer } from "./slicer";
import type { PrintSettings } from "@/editor/stores/settingsStore";

export interface GcodeResult {
  gcode: string;
  totalFilament: number; // mm
  totalTime: number;     // seconds (rough estimate)
  layerCount: number;
}

/**
 * Generate G-code from sliced layers.
 */
export function generateGcode(
  layers: SliceLayer[],
  settings: PrintSettings,
  boundingBox: { min: { x: number; y: number; z: number }; max: { x: number; y: number; z: number } }
): GcodeResult {
  const lines: string[] = [];
  let totalFilament = 0;
  let totalDistance = 0;
  let currentX = 0;
  let currentY = 0;
  let currentZ = 0;

  const eStepsPerMM = (settings.nozzleDiameter * settings.nozzleDiameter * Math.PI / 4) /
    (settings.filamentDiameter * settings.filamentDiameter * Math.PI / 4);
  let ePos = 0;

  // Helper: add a move command
  const addMove = (x: number, y: number, z: number, extrude: boolean, speed: number, comment?: string) => {
    const dx = x - currentX;
    const dy = y - currentY;
    const dz = z - currentZ;
    const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);

    if (extrude && dist > 0) {
      const eDelta = dist * eStepsPerMM;
      ePos += eDelta;
      totalFilament += eDelta;
    }

    lines.push(`G1 X${x.toFixed(3)} Y${y.toFixed(3)} Z${z.toFixed(3)} F${(speed * 60).toFixed(0)}${extrude && dist > 0 ? ` E${ePos.toFixed(5)}` : ""}${comment ? ` ; ${comment}` : ""}`);
    totalDistance += dist;
    currentX = x;
    currentY = y;
    currentZ = z;
  };

  // Header
  lines.push("; Generated by BlenderGL");
  lines.push(`; Layer height: ${settings.layerHeight}mm`);
  lines.push(`; Infill: ${settings.infillDensity}%`);
  lines.push(`; Walls: ${settings.wallCount}`);
  lines.push("");
  lines.push("G28 ; Home all axes");
  lines.push("G92 E0 ; Reset extruder");
  lines.push(`M104 S${settings.extruderTemp} ; Set hotend temp`);
  lines.push(`M140 S${settings.bedTemp} ; Set bed temp`);
  lines.push("M190 S0 ; Wait for bed temp");
  lines.push("M109 S0 ; Wait for hotend temp");
  lines.push("G90 ; Absolute positioning");
  lines.push("M82 ; Absolute extruder");
  lines.push("");

  // Adhesion
  if (settings.adhesionType === "brim" || settings.adhesionType === "skirt") {
    const brimOffset = settings.adhesionType === "brim" ? settings.nozzleDiameter * 2 : 3;
    const brimX = boundingBox.min.x - brimOffset;
    const brimY = boundingBox.min.y - brimOffset;
    const brimW = boundingBox.max.x - boundingBox.min.x + brimOffset * 2;
    const brimH = boundingBox.max.y - boundingBox.min.y + brimOffset * 2;

    lines.push(`; ${settings.adhesionType}`);
    const firstZ = layers[0]?.z ?? settings.layerHeight;
    // Move to brim start
    lines.push(`G0 X${brimX.toFixed(3)} Y${brimY.toFixed(3)} Z${firstZ.toFixed(3)} F${(settings.travelSpeed * 60).toFixed(0)}`);
    currentX = brimX;
    currentY = brimY;
    currentZ = firstZ;

    // Draw brim rectangle
    const brimPerimeter = [
      { x: brimX + brimW, y: brimY },
      { x: brimX + brimW, y: brimY + brimH },
      { x: brimX, y: brimY + brimH },
      { x: brimX, y: brimY },
    ];
    for (const p of brimPerimeter) {
      addMove(p.x, p.y, firstZ, true, settings.printSpeed, "brim");
    }
    lines.push("");
  }

  // Layer-by-layer
  for (let li = 0; li < layers.length; li++) {
    const layer = layers[li];
    lines.push(`; Layer ${li} (Z=${layer.z.toFixed(3)})`);

    // Move to first contour point
    for (const contour of layer.contours) {
      if (contour.length === 0) continue;

      // Travel to contour start
      addMove(contour[0].x, contour[0].y, layer.z, false, settings.travelSpeed, "travel");

      // Print contour (perimeter)
      for (let i = 1; i < contour.length; i++) {
        const speed = i <= 1 ? settings.outerWallSpeed : settings.innerWallSpeed;
        addMove(contour[i].x, contour[i].y, layer.z, true, speed, "perimeter");
      }
      // Close contour
      if (contour.length > 2) {
        addMove(contour[0].x, contour[0].y, layer.z, true, settings.innerWallSpeed, "perimeter close");
      }
    }

    // Simple infill: horizontal lines across the bounding box
    if (settings.infillDensity > 0 && layer.contours.length > 0) {
      const infillSpacing = (100 / settings.infillDensity) * settings.nozzleDiameter;
      const minY = boundingBox.min.y;
      const maxY = boundingBox.max.y;
      const minX = boundingBox.min.x;
      const maxX = boundingBox.max.x;

      for (let y = minY; y <= maxY; y += infillSpacing) {
        addMove(minX, y, layer.z, false, settings.travelSpeed, "infill travel");
        addMove(maxX, y, layer.z, true, settings.infillSpeed, "infill");
      }
    }

    lines.push("");
  }

  // Footer
  lines.push("; End of print");
  lines.push("M104 S0 ; Turn off hotend");
  lines.push("M140 S0 ; Turn off bed");
  lines.push("G28 X Y ; Home X Y");
  lines.push("M84 ; Disable motors");
  lines.push("M400 ; Wait for moves to finish");

  // Rough time estimate
  const printTime = totalDistance / settings.printSpeed; // seconds

  return {
    gcode: lines.join("\n"),
    totalFilament,
    totalTime: printTime,
    layerCount: layers.length,
  };
}

/**
 * Download G-code as a text file.
 */
export function downloadGcode(gcode: string, filename = "print.gcode"): void {
  const blob = new Blob([gcode], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
